services:
  postgres-migrations:
    container_name: postgres-migrations
    build:
      context: docker
      dockerfile: postgres.Dockerfile
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    environment:
      POSTGRES_MULTIPLE_DATABASES: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: developer
      PGDATA: "/var/lib/postgres/data/pgdata"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: no
    ports:
      - "5433:5432"

  atlas-diff:
    container_name: atlas-diff
    user: ${CURRENT_UID}
    image: arigaio/atlas:latest
    command: migrate diff --to file://schema/models.sql,file://schema/indexes.sql --env docker
    depends_on:
      postgres-migrations:
        condition: service_healthy
    links:
      - postgres-migrations
    volumes:
      - ./migrations:/migrations
      - ./schema:/schema
      - ./atlas.hcl:/atlas.hcl

  atlas-lint:
    container_name: atlas-lint
    user: ${CURRENT_UID}
    image: arigaio/atlas:latest
    command: migrate lint --env docker --latest 5
    depends_on:
      atlas-diff:
        condition: service_completed_successfully
      postgres-migrations:
        condition: service_healthy
    links:
      - postgres-migrations
    volumes:
      - ./atlas.hcl:/atlas.hcl
      - ./migrations:/migrations
      - ./schema:/schema

  atlas-apply:
    container_name: atlas-apply
    user: ${CURRENT_UID}
    image: arigaio/atlas:latest
    command: migrate apply --env docker
    depends_on:
      postgres-migrations:
        condition: service_healthy
    links:
      - postgres-migrations
    volumes:
      - ./atlas.hcl:/atlas.hcl
      - ./migrations:/migrations
      - ./schema:/schema
