{{- if .Values.configmap.configMapValues }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: stroppy-cloud-pannel-configmap-values
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.configmap.configMapValues }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}

{{- if .Values.configmap.yamlFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: stroppy-cloud-pannel-yaml-files
  namespace: {{ .Release.Namespace }}
data:
  {{- range $fileName, $fileContent := .Values.configmap.yamlFiles }}
  {{ $fileName }}: |
    {{ $fileContent | indent 4 | trim }}
  {{- end }}
{{- end }}

{{- if .Values.configmap.jsonFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: stroppy-cloud-pannel-json-files
  namespace: {{ .Release.Namespace }}
data:
  {{- range $fileName, $fileContent := .Values.configmap.jsonFiles }}
  {{ $fileName }}: |
    {{ $fileContent | indent 4 | trim }}
  {{- end }}
{{- end }}

{{- if .Values.configmap.customFiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: stroppy-cloud-pannel-custom-files
  namespace: {{ .Release.Namespace }}
data:
  {{- range $fileName, $fileContent := .Values.configmap.customFiles }}
  {{ $fileName }}: |
    {{ $fileContent | indent 4 | trim }}
  {{- end }}
{{- end }}