apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stroppy-cloud-pannel.fullname" . }}
  labels:
    {{- include "stroppy-cloud-pannel.labels" . | nindent 4 }}
spec:
  {{- if not (index .Values "stroppy-cloud-pannel").autoscaling.enabled }}
  replicas: {{ (index .Values "stroppy-cloud-pannel").replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: stroppy-cloud-pannel
  template:
    metadata:
      {{- with (index .Values "stroppy-cloud-pannel").podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "stroppy-cloud-pannel.labels" . | nindent 10 }}
        {{- if (index .Values "stroppy-cloud-pannel").extraPodLabels }}
        {{- include "stroppy-cloud-pannel.extraPodLabels" . | nindent 10 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "stroppy-cloud-pannel.serviceAccountName" . }}
      securityContext:
        {{- toYaml (index .Values "stroppy-cloud-pannel").podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml (index .Values "stroppy-cloud-pannel").securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if (index .Values "stroppy-cloud-pannel").command }}
          command: {{ (index .Values "stroppy-cloud-pannel").command  }}
          {{- end }}
          {{- if (index .Values "stroppy-cloud-pannel").args  }}
          args: {{ (index .Values "stroppy-cloud-pannel").args  }}
          {{- end }}
          env:
          {{- if .Values.configmap.yamlFiles }}
            - name: CONFIG_PATH
              value: "/etc/config/"
          {{- end }}
          {{- range $key, $value := .Values.env }}
            - name: {{ quote $key }}
              {{- if or (typeIs "string" $value) (typeIs "int" $value) (typeIs "float64" $value) (typeIs "bool" $value) }}
              value: {{ $value | quote }}
              {{- else if hasKey $value "secretKeyRef" }}
              valueFrom:
                secretKeyRef:
                  name: {{ quote $value.secretKeyRef.name }}
                  key: {{ quote $value.secretKeyRef.key }}
              {{- else if hasKey $value "configMapKeyRef" }}
              valueFrom:
                configMapKeyRef:
                  name: {{ quote $value.configMapKeyRef.name }}
                  key: {{ quote $value.configMapKeyRef.key }}
              {{- end }}
          {{- end }}
          {{- range $key, $value := (index .Values "stroppy-cloud-pannel").env  }}
            - name: {{ quote $key }}
              {{- if or (typeIs "string" $value) (typeIs "int" $value) (typeIs "float64" $value) (typeIs "bool" $value) }}
              value: {{ $value | quote }}
              {{- else if hasKey $value "secretKeyRef" }}
              valueFrom:
                secretKeyRef:
                  name: {{ quote $value.secretKeyRef.name }}
                  key: {{ quote $value.secretKeyRef.key }}
              {{- else if hasKey $value "configMapKeyRef" }}
              valueFrom:
                configMapKeyRef:
                  name: {{ quote $value.configMapKeyRef.name }}
                  key: {{ quote $value.configMapKeyRef.key }}
              {{- end }}
          {{- end }}
          ports:
          {{- range $k, $v := (index .Values "stroppy-cloud-pannel").appPorts }}
            - name: {{ $k }}
              containerPort: {{ $v }}
              protocol: TCP
          {{- end }}
          {{- if (index .Values "stroppy-cloud-pannel").livenessProbe }}
          livenessProbe:
            {{- toYaml (index .Values "stroppy-cloud-pannel").livenessProbe | nindent 12 }}
          {{- end }}
          {{- if (index .Values "stroppy-cloud-pannel").readinessProbe }}
          readinessProbe:
            {{- toYaml (index .Values "stroppy-cloud-pannel").readinessProbe | nindent 12 }}
          {{- end }}
          {{- if (index .Values "stroppy-cloud-pannel").resources }}
          resources:
            {{- toYaml (index .Values "stroppy-cloud-pannel").resources | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.configmap.yamlFiles }}
          - name: config-volume
            mountPath: /etc/config
            readOnly: true
          {{- end }}
          {{- if  (index .Values "stroppy-cloud-pannel").extraVolumeMounts }}
          {{- toYaml (index .Values "stroppy-cloud-pannel").extraVolumeMounts | nindent 12 -}}
          {{- end }}
      ### Extra containers
      {{- if  (index .Values "stroppy-cloud-pannel").extraContainers }}
      {{- range  (index .Values "stroppy-cloud-pannel").extraContainers  }}
        - name: {{ .name }}
          image: "{{ .image }}:{{ .tag }}"
          imagePullPolicy: {{ .imagePullPolicy | default "IfNotPresent" }}
          {{- if .command }}
          command: {{ .command | toYaml | nindent 12 }}
          {{- end }}
          {{- if .args }}
          args: {{ .args | toYaml | nindent 12 }}
          {{- end }}
          {{- if .env }}
          env:
          {{- range $key, $value := .env  }}
            - name: {{ quote $key }}
              {{- if or (typeIs "string" $value) (typeIs "int" $value) (typeIs "float64" $value) (typeIs "bool" $value) }}
              value: {{ $value | quote }}
              {{- else if hasKey $value "secretKeyRef" }}
              valueFrom:
                secretKeyRef:
                  name: {{ quote $value.secretKeyRef.name }}
                  key: {{ quote $value.secretKeyRef.key }}
              {{- else if hasKey $value "configMapKeyRef" }}
              valueFrom:
                configMapKeyRef:
                  name: {{ quote $value.configMapKeyRef.name }}
                  key: {{ quote $value.configMapKeyRef.key }}
              {{- end }}
          {{- end }}
          {{- end}}
          {{- if .ports }}
          ports:
          {{- toYaml .ports | nindent 12 }}
          {{- end }}
          {{- if .livenessProbe }}
          livenessProbe:
            {{- toYaml .livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .readinessProbe }}
          readinessProbe:
            {{- toYaml .readinessProbe | nindent 12 }}
          {{- end }}
          {{- if .resources }}
          resources:
            {{- toYaml .resources | nindent 12 }}
          {{- end }}
          {{- if  .extraVolumeMounts }}
          volumeMounts:
          {{- toYaml .extraVolumeMounts | nindent 12 -}}
          {{ end }}
      {{- end }}
      {{- end }}
################
      volumes:
      {{- if .Values.configmap.yamlFiles }}
      - name: config-volume
        configMap:
          name: stroppy-cloud-pannel-yaml-files
      {{- end }}
      {{- if (index .Values "stroppy-cloud-pannel").extraVolumes }}
      {{- toYaml (index .Values "stroppy-cloud-pannel").extraVolumes | nindent 8 }}
      {{- end }}
      {{- with  (index .Values "stroppy-cloud-pannel").nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (index .Values "stroppy-cloud-pannel").affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with (index .Values "stroppy-cloud-pannel").tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}