{{- range $secretName, $secretData := (index .Values "stroppy-cloud-pannel").secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "stroppy-cloud-pannel.labels" $ | nindent 4 }}
  annotations:
    {{- with (index $.Values "stroppy-cloud-pannel").secretsAnnotations  }}
    {{- . | toYaml | nindent 4 }}
    {{- end }}
    cheksum: {{ $secretData | toYaml | sha256sum }}
data:
  {{- range $dataKey, $dataValue := $secretData }}
  {{- $dataKey | nindent 2 }}: {{ $dataValue | toString | b64enc }}
  {{- end }}
{{- end }}
