{{- if (index .Values "stroppy-cloud-pannel").serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "stroppy-cloud-pannel.serviceAccountName" . }}
  labels:
    {{- include "stroppy-cloud-pannel.labels" . | nindent 4 }}
  {{- $annotations := dict }}
  {{- with (index .Values "stroppy-cloud-pannel").serviceAccount.annotations}}
  {{- $annotations = merge $annotations . }}
  {{- end }}

  {{- if not (empty $annotations) }}
  annotations:
  {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- end }}
